name: Update RSS Feed

on:
  schedule:
    - cron: "0 8 * * *"   # runs every day at 9:00 UTC
    # Weekly Friday at 5 PM Lagos (16 UTC)
    - cron: "0 16 * * FRI"
  workflow_dispatch:       # lets you trigger manually

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: |
          python update_feed.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add feed.xml
          git commit -m "Automated update"
          git push
